### ISSUE TITLE
use different icon for sharing widget

### ISSUE THREAD

**Issue by derekeder** [datamade/django-councilmatic-notifications#10]
clicking on a star icon is not very intuitive for sharing a widget.

<img width="812" alt="screen shot 2016-12-12 at 10 41 05 am" src="https://cloud.githubusercontent.com/assets/919583/21107514/91b4a5fa-c057-11e6-8e41-80f4bdd56a72.png">

Let's instead use the [code](http://fontawesome.io/icon/code/) icon and put the word 'Embed' next to it

**Comment by reginafcompton** [comment]
Okay. New icon and text added. Not convinced, though.....

<img width="682" alt="screen shot 2016-12-15 at 4 46 30 pm" src="https://cloud.githubusercontent.com/assets/13078679/21245057/24028e64-c2e6-11e6-9013-355b39ad8058.png">
