### ISSUE TITLE
"Send my notifications email" not working?

### ISSUE THREAD

**Issue by derekeder** [datamade/django-councilmatic-notifications#11]
This button is not working for me (user name "derek")

<img width="381" alt="screen shot 2016-12-12 at 2 05 11 pm" src="https://cloud.githubusercontent.com/assets/919583/21114879/4d1cfc0e-c074-11e6-850c-646447db1566.png">

Also, when I click it, is there any notification that's supposed to fire? A flash message would be appropriate.

**Comment by evz** [comment]
It's supposed to send you an email if there are updates to anything that you are subscribed to. I can add a flash message but it's really only going to send anything if there are updates to send. I'll see if there is a quick way to calculate the update counts and create an appropriate alert one way or the other.

**Comment by reginafcompton** [comment]
Alerts work like so:

<img width="1219" alt="screen shot 2016-12-19 at 10 42 18 am" src="https://cloud.githubusercontent.com/assets/13078679/21321928/7dd7082c-c5dc-11e6-94d9-2ab5590569bd.png">


<img width="1228" alt="screen shot 2016-12-19 at 11 15 00 am" src="https://cloud.githubusercontent.com/assets/13078679/21321940/87c93eb8-c5dc-11e6-8c8c-e77ecd9ffc1f.png">
