### ISSUE TITLE
subscribe/embed label formatting

### ISSUE THREAD

**Issue by derekeder** [datamade/django-councilmatic-notifications#15]
Let's make the embed & subscribe labels more consistent throughout the site.

Let's pull them out of the H1 and make them look like link to 'view on the city council website'

Something like this:

<img width="334" alt="screen shot 2016-12-19 at 5 02 05 pm" src="https://cloud.githubusercontent.com/assets/919583/21332267/e8c89a4e-c60c-11e6-968c-38fc1bf138bf.png">

Lets make this consistent on every page, where possible. They could be combined on the Committee detail page, for example: https://nyc-staging.councilmatic.org/committee/committee-on-aging-cd4b6e200ed9/

**Comment by reginafcompton** [comment]
Done and on the staging site, e.g. https://nyc-staging.councilmatic.org/person/corey-d-johnson-b377aefa3cfe/
