### ISSUE TITLE
Activation email could be more concise

### ISSUE THREAD

**Issue by fgregg** [datamade/django-councilmatic-notifications#2]
![screenshot from 2016-11-30 17-04-51](https://cloud.githubusercontent.com/assets/536941/20775154/3395de30-b71f-11e6-8793-4039ba877f24.png)

Don't make me scroll down to authorize.

**Comment by reginafcompton** [comment]
Here's a solution. I'll close issue, for now, but feed back is welcome.



<img width="738" alt="screen shot 2016-12-14 at 4 53 04 pm" src="https://cloud.githubusercontent.com/assets/13078679/21204633/e8f8abb4-c21d-11e6-8847-fe64066d9a7e.png">
