### ISSUE TITLE
If no stylesheet, links for rss don't show up

### ISSUE THREAD

**Issue by fgregg** [datamade/django-councilmatic-notifications#4]
![screenshot from 2016-12-05 10-46-25](https://cloud.githubusercontent.com/assets/536941/20893646/21560c38-bad8-11e6-926d-e1997ff4103b.png)

**Comment by reginafcompton** [comment]
I added all the styles inline, since email clients do not know about external style sheets. (http://www.benchmarkemail.com/help-FAQ/answer/Using-CSS-in-HTML-emails)
