### ISSUE TITLE
Visual indication that I'm subscribed to event is confusing

### ISSUE THREAD

**Issue by fgregg** [datamade/django-councilmatic-notifications#5]
It' looks very similar to the RSS link.

**Comment by reginafcompton** [comment]
Added a more descriptive tooltip and also a modal popup when you decide to subscribe. 


<img width="666" alt="screen shot 2016-12-15 at 2 12 53 pm" src="https://cloud.githubusercontent.com/assets/13078679/21240389/b614814c-c2d0-11e6-8e39-737178f330a9.png">
