### ISSUE TITLE
add alert when email subscription is added

### ISSUE THREAD

**Issue by derekeder** [datamade/django-councilmatic-notifications#8]
When subscribing to an email alert, the only feedback the user gets is the 'bullhorn' icon changes.

<img width="756" alt="screen shot 2016-12-12 at 10 30 45 am" src="https://cloud.githubusercontent.com/assets/919583/21107093/256f08f0-c056-11e6-8db2-b35574b8fd2d.png">

Let's have it also send a flash message like "You have been subscribed to "Search term: controlling_body: Committee on Public Safety"

**Comment by reginafcompton** [comment]
Done. 


<img width="1266" alt="screen shot 2016-12-15 at 2 10 50 pm" src="https://cloud.githubusercontent.com/assets/13078679/21240303/5a9cf4f2-c2d0-11e6-9607-faa8d5c5be4e.png">
