### ISSUE TITLE
consolodate subscription tools in one place

### ISSUE THREAD

**Issue by derekeder** [datamade/django-councilmatic-notifications#9]
So right now, we have two icons that indicate subscription options. I propose we consolidate these into one icon with the text 'subscribe' that opens up a modal with subscription options:

1. RSS
2. Daily email alerts

Each would have a description about the updates. I especially think this is important for email alerts as there are details to share, like how often they'll get emails and how to manage their subscriptions.

**Comment by reginafcompton** [comment]
Did this: 

<img width="1254" alt="screen shot 2016-12-15 at 4 05 37 pm" src="https://cloud.githubusercontent.com/assets/13078679/21243860/79efdcf6-c2e0-11e6-92b5-4c75e6a7b569.png">
